name = "game-list"
main = ".open-next/worker.js"
compatibility_date = "2026-06-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# 🌍 اتصال دیتابیس برای نسخه اصلی (Production)
[[kv_namespaces]]
binding = "GAME_KV"
id = "738198ef9ce548f3a22e30310da8ea85"

# 🧪 اتصال دیتابیس برای نسخه‌های پیش‌نمایش (Preview)
[env.preview]
[[env.preview.kv_namespaces]]
binding = "GAME_KV"
id = "738198ef9ce548f3a22e30310da8ea85"

[vars]
NEXT_ANALYTICS_ID = ""
