name = "game-list"
main = ".open-next/worker.js"
compatibility_date = "2026-06-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "GAME_KV"
id = "738198ef9ce548f3a22e30310da8ea85"

[vars]
NEXT_ANALYTICS_ID = ""

